@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.guidebook.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;