@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.guidebook.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;