@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.guidebook;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;