@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.guidebook.guidebook;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;