@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.guidebook.guidebook.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;