@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.guidebook.guidebook.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;